### ISSUE TITLE
Tabellenblatt Daten

### ISSUE THREAD

**Issue by Markus1995** [derhasi/auswertung-light#1]
Hallo,

wie ist das Tabellenblatt Daten aufgebaut?
Was ich bisher rausgefunden habe, ist, dass in A die LizenzNr. steht, in B die Klasse, in C der Nachname, in D der Vorname.

Aber was steht in den anderen?

Vielen Dank für die super Tabelle.

MFG

Markus

**Comment by derhasi** [comment]
@Markus1995 
Ich habe eine [Beispiel CSV](https://github.com/derhasi/auswertung-light/blob/master/daten-beispiel.csv) hier hinzugefügt und die Spalten der README ergänzt. Ich hoffe das hilft.

In welchem Kontext, für welchen Verein oder Meisterschaft willst du das Projekt einsetzen?

**Comment by Markus1995** [comment]
Super, vielen Dank.

Ich möchte das Programm gerne für den Schwabenpokal verwenden bzw. als Vorlage nehmen.

Dafür ist es aber noch ein bisschen zu umfangreich.

**Comment by derhasi** [comment]
@Markus1995, dann sollten wir vielleicht mal telefonieren. Meine Mobilnummer steht im Excel-File.

**Comment by Markus1995** [comment]
@derhasi, habe dir eine Email geschrieben

**Comment by Markus1995** [comment]
@derhasi, ich hoffe, dass die Email-Adresse im Excel-File noch stimmt.

**Comment by derhasi** [comment]
Jep, dann mach ich hiermal das Issue zu :)
